---

- name: "MEDIIUM | CNTR-K8-000150 | PATCH | The Kubernetes Controller Manager must use TLS 1.2, at a minimum, to protect the confidentiality of sensitive data during electronic dissemination."
  lineinfile:
      path: "{{ controller_manager_pod_specification_file }}"
      regexp: '^(\s+- --tls-min-version.*)$'
      line: "    - --tls-min-version={{ cntrk8stig_kube_controller_manager_tls }}"
      insertafter: '^\s+- kube-controller-manager$'
  when:
      - cntr_k8_000150
      - kubernetes_master
  tags:
      - CNTR-K8-000150
      - CAT2
      - CCI-000068
      - SRG-APP-000014-CTR-000035
      - SV-242376r712484_rule
      - V-242376
      - ssh
      - kube_control_manager

- name: "MEDIUM | CNTR-K8-000160 | PATCH | The Kubernetes Scheduler must use TLS 1.2, at a minimum, to protect the confidentiality of sensitive data during electronic dissemination."
  lineinfile:
      path: "{{ scheduler_pod_specification_file }}"
      regexp: '^(\s+- --tls-min-version.*)$'
      line: "    - --tls-min-version={{ cntrk8stig_kube_scheduler_manager_tls }}"
      insertafter: '^\s+- kube-scheduler'
  when:
      - cntr_k8_000160
      - kubernetes_master
  tags:
      - CNTR-K8-000160
      - CAT2
      - CCI-000068
      - SRG-APP-000014-CTR-000035
      - SV-242377r712487_rule
      - V-242377
      - kube_scheduler

- name: "MEDIUM | CNTR-K8-000170 | PATCH | The Kubernetes API Server must use TLS 1.2, at a minimum, to protect the confidentiality of sensitive data during electronic dissemination."
  lineinfile:
      path: "{{ api_server_pod_specification_file }}"
      regexp: '^(\s+- --tls-min-version.*)$'
      line: "    - --tls-min-version={{ cntrk8stig_kube_api_server_tls }}"
      insertafter: '^\s+- kube-apiserver'
  when:
      - cntr_k8_000170
      - kubernetes_master
  tags:
      - CNTR-K8-000170
      - CAT2
      - CCI-000068
      - SRG-APP-000014-CTR-000040
      - SV-242378r712490_rule
      - V-242378
      - kube_api_server

- name: "MEDIUM | CNTR-K8-000180 | PATCH | The Kubernetes etcd must use TLS to protect the confidentiality of sensitive data during electronic dissemination."
  lineinfile:
      path: "{{ etcd_pod_specification_file }}"
      regexp: '^(\s+- --auto-tls=.*)$'
      line: "    - --auto-tls=false"
      insertafter: '^\s+- etcd'
  when:
      - cntr_k8_000180
      - kubernetes_master
  tags:
      - CNTR-K8-000180
      - CAT2
      - CCI-000068
      - SRG-APP-000014-CTR-000035
      - SV-242379r754799_rule
      - V-242379
      - kube_etcd

- name: "MEDIUM | CNTR-K8-000190 | PATCH | The Kubernetes etcd must use TLS to protect the confidentiality of sensitive data during electronic dissemination."
  lineinfile:
      path: "{{ etcd_pod_specification_file }}"
      regexp: '^(\s+- --peer-auto-tls=.*)$'
      line: "    - --peer-auto-tls=false"
      insertafter: '^\s+- etcd'
  when:
      - cntr_k8_000190
      - kubernetes_master
  tags:
      - CNTR-K8-000190
      - CAT2
      - CCI-000068
      - SRG-APP-000014-CTR-000035
      - SV-242380r754800_rule
      - V-242380
      - kube_etcd

- name: "MEDIUM | CNTR-K8-000270 | PATCH | The Kubernetes API Server must enable Node,RBAC as the authorization mode."
  lineinfile:
      path: "{{ api_server_pod_specification_file }}"
      regexp: '^(\s+- --authorization-mode.*)$'
      line: "    - --authorization-mode=Node,RBAC"
      insertafter: '^\s+- kube-apiserver'
  when:
      - cntr_k8_000270
      - kubernetes_master
  tags:
      - CNTR-K8-000270
      - CAT2
      - CCI-000213
      - SRG-APP-000033-CTR-000090
      - SV-242382r712502_rule
      - V-242382
      - kube_api_server

- name: "MEDIUM | CNTR-K8-000300 | PATCH | The Kubernetes Scheduler must have secure binding."
  lineinfile:
      path: "{{ scheduler_pod_specification_file }}"
      regexp: '^(\s+- --bind-address.*)$'
      line: "    - --bind-address=127.0.0.1"
      insertafter: '^\s+- kube-scheduler'
  when:
      - cntr_k8_000300
      - kubernetes_master
  tags:
      - CNTR-K8-000300
      - CAT2
      - CCI-000213
      - SRG-APP-000033-CTR-000090
      - SV-242384r712508_rule
      - V-242384
      - kube_scheduler

- name: "MEDIUM | CNTR-K8-000310 | PATCH | The Kubernetes Controller Manager must have secure binding."
  lineinfile:
      path: "{{ controller_manager_pod_specification_file }}"
      regexp: '^(\s+- --bind-address.*)$'
      line: "    - --bind-addressn=127.0.0.1"
      insertafter: '^\s+- kube-controller-manager$'
  when:
      - cntr_k8_000310
      - kubernetes_master
  tags:
      - CNTR-K8-000310
      - CAT2
      - CCI-000213
      - SRG-APP-000033-CTR-000090
      - SV-242385r712511_rule
      - V-242385
      - kube_control_manager

- name: "MEDIUM | CNTR-K8-000350 | PATCH | The Kubernetes API server must have the secure port set."
  lineinfile:
      path: "{{ api_server_pod_specification_file }}"
      regexp: '^(\s+- --secure-port.*)$'
      line: "    - --secure-port={{ cntrk8stig_kube_api_server_secure_port }}"
      insertafter: '^\s+- kube-apiserver'
  when:
      - cntr_k8_000350
      - kubernetes_master
  tags:
      - CNTR-K8-000350
      - CAT2
      - CCI-000213
      - SRG-APP-000033-CTR-000100
      - SV-242389r712523_rule
      - V-242389
      - kube_api_server

- name: |
      "MEDIUM | CNTR-K8-000400 | PATCH | Kubernetes Worker Nodes must not have sshd service running."
      "MEDIUM | CNTR-K8-000410 | PATCH | Kubernetes Worker Nodes must not have the sshd service enabled."
  systemd:
      name: sshd
      state: stopped
      enabled: false
  when:
      - kubernetes_master
      - "'sshd' in ansible_facts.packages"
      - cntr_k8_000400 or
        cntr_k8_000410
  tags:
      - CNTR-K8-000400
      - CNTR-K8-000410
      - CAT2
      - CCI-000213
      - SRG-APP-000033-CTR-000100
      - SRG-APP-000033-CTR-000095
      - SV-242389r712523_rule
      - SV-242394r717017_rule
      - V-242389
      - V-242394
      - sshd

- name: "MEDIUM | CNTR-K8-000420 | PATCH | Kubernetes dashboard must not be enabled."
  block:
      - name: "MEDIUM | CNTR-K8-000420 | PATCH | Kubernetes dashboard must not be enabled. | Get if dashboard available"
        shell: kubectl get pods --all-namespaces -l k8s-app=kubernetes-dashboard
        changed_when: false
        failed_when: false
        register: cntr_k8_000420_kube_dash_status

      - name: "MEDIUM | CNTR-K8-000420 | PATCH | Kubernetes dashboard must not be enabled. | Remove dashboard if exists"
        shell: kubectl delete deployment kubernetes-dashboard --namespace=kube-system
        changed_when: true
        when: cntr_k8_000420_kube_dash_status.stdout | length >=1
  when:
      - cntr_k8_000420
  tags:
      - CNTR-K8-000420
      - CAT2
      - CCI-000213
      - SRG-APP-000033-CTR-000095
      - SV-242395r712541_rule
      - V-242395
      - kube_dashboard

- name: "MEDIUM | CNTR-K8-000430 | PATCH | Kubernetes Kubectl cp command must give expected access and results."
  block:
      - name: "MEDIUM | CNTR-K8-000430 | PATCH | Kubernetes Kubectl cp command must give expected access and results. | Get Client version"
        shell: kubectl version --short | grep "Client Version" | cut -d"v" -f2
        changed_when: false
        failed_when: false
        register: cntr_k8_000430_kubectl_client_version

      - name: "MEDIUM | CNTR-K8-000430 | PATCH | Kubernetes Kubectl cp command must give expected access and results. | Message out version"
        debug:
            msg:
                - "Warning!! Your version needs to be 1.12.9 or newer"
        when: cntr_k8_000430_kubectl_client_version.stdout >= 1.12.0

      - name: "MEDIUM | CNTR-K8-000430 | PATCH | Kubernetes Kubectl cp command must give expected access and results. | Warning count"
        set_fact:
            control_number: "{{ control_number }} + [ 'CNTR-K8-000430' ]"
            warn_count: "{{ warn_count | int + 1 }}"
        when: cntr_k8_000430_kubectl_client_version.stdout >= 1.12.0
  when:
      - cntr_k8_000430
  tags:
      - CNTR-K8-000430
      - CAT2
      - CCI-000213
      - SRG-APP-000033-CTR-000090
      - SV-242396r712544_rule
      - V-242396
      - kubectl

- name: "MEDIUM | CNTR-K8-000450 | PATCH | Kubernetes DynamicAuditing must not be enabled."
  block:
      - name: "MEDIUM | CNTR-K8-000450 | PATCH | Kubernetes DynamicAuditing must not be enabled. | Get feature-gates files"
        shell: grep -is feature-gates /etc/kubernetes/manifests/* /etc/sysconfig/kublet | cut -d":" -f1
        changed_when: false
        failed_when: false
        register: cntr_k8_000450_feature_gates_files

      - name: "MEDIUM | CNTR-K8-000450 | PATCH | Kubernetes DynamicAuditing must not be enabled. | Update DynamicAuditing"
        replace:
            path: "{{ item }}"
            regexp: 'DynamicAuditing=true'
            replace: "DynamicAuditing=false"
        with_items:
            - "{{ cntr_k8_000450_feature_gates_files.stdout_lines }}"
        when: cntr_k8_000450_feature_gates_files.stdout | length >=1
  when:
      - cntr_k8_000450
      - kubernetes_master
  tags:
    - CNTR-K8-000450
    - CAT2
    - CCI-000213
    - SRG-APP-000033-CTR-000100
    - SV-242398r717019_rule
    - V-242398
    - kube_api_server

# - name: "MEDIUM | CNTR-K8-000460 | PATCH | Kubernetes DynamicKubeletConfig must not be enabled."
#   block:
#       - name: "MEDIUM | CNTR-K8-000460 | PATCH | Kubernetes DynamicKubeletConfig must not be enabled. | Get feature-gates files"
#         shell: grep -is feature-gates /etc/kubernetes/manifests/* /etc/sysconfig/kublet | cut -d":" -f1
#         changed_when: false
#         failed_when: false
#         register: cntr_k8_000450_feature_gates_files

#       - name: "MEDIUM | CNTR-K8-000460 | PATCH | Kubernetes DynamicKubeletConfig must not be enabled. | Update DynamicKubeletConfig"
#         replace:
#             path: "{{ item }}"
#             regexp: 'DynamicKubeletConfig=true'
#             replace: "DynamicAuditing=false"
#         with_items:
#             - "{{ cntr_k8_000450_feature_gates_files.stdout_lines }}"
#         when: cntr_k8_000450_feature_gates_files.stdout | length >=1
#   when:
#       - cntr_k8_000460
#   tags:
#       - CNTR-K8-000460
#       - CAT2
#       - CCI-000213
#       - SRG-APP-000033-CTR-000095
#       - SV-242399r717021_rule
#       - V-242399
#       - kube_api_server
