---

# - name: Gather the package facts before prelim
#   package_facts:
#       manager: auto
#   tags:
#       - always

# - import_tasks: prelim.yml
#   tags:
#       - always

- name: Gather package facts after prelim
  package_facts:
      manager: auto
  tags:
      - always

- name: Include CAT I patches
  import_tasks: fix-cat1.yml
  when: cntrk8stig_cat1_patch
  tags:
      - cat1
      - high
