---

# - name: Gather the package facts before prelim
#   package_facts:
#       manager: auto
#   tags:
#       - always

# - import_tasks: prelim.yml
#   tags:
#       - always

- name: Gather package facts after prelim
  package_facts:
      manager: auto
  tags:
      - always

- name: Include CAT I patches
  import_tasks: fix-cat1.yml
  when: cntrk8stig_cat1_patch
  tags:
      - cat1
      - high

- name: flush handlers
  meta: flush_handlers

- name: Display warning counts and related control IDs
  debug:
      msg: "You have {{ warn_count }} Warning(s) that require investigation that are related to the following control ID(s) {{ control_number }}"
  when: warn_count != 0
  tags:
      - always
